name: strandseqnation
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.2=py37h516909a_0
  - appdirs=1.4.3=py_1
  - async-timeout=3.0.1=py_1000
  - attrs=19.3.0=py_0
  - bcftools=1.10.2=hd2cd319_0
  - bcrypt=3.1.7=py37h516909a_0
  - bedops=2.4.39=hc9558a2_0
  - binutils_impl_linux-64=2.33.1=h53a641e_8
  - binutils_linux-64=2.33.1=h9595d00_17
  - bioconductor-biobase=2.42.0=r351h14c3975_1
  - bioconductor-biocgenerics=0.28.0=r351_1
  - bioconductor-biocinstaller=1.32.1=r351_0
  - bioconductor-biocparallel=1.16.6=r351h1c2f66e_0
  - bioconductor-biostrings=2.50.2=r351h14c3975_0
  - bioconductor-bsgenome=1.50.0=r351_0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.1=r351_5
  - bioconductor-complexheatmap=2.0.0=r351_0
  - bioconductor-delayedarray=0.8.0=r351h14c3975_0
  - bioconductor-fastseg=1.28.0=r351hf484d3e_1
  - bioconductor-genomeinfodb=1.18.1=r351_0
  - bioconductor-genomeinfodbdata=1.2.1=r351_0
  - bioconductor-genomicalignments=1.18.1=r351h14c3975_0
  - bioconductor-genomicranges=1.34.0=r351h14c3975_0
  - bioconductor-iranges=2.16.0=r351h14c3975_0
  - bioconductor-rsamtools=1.34.0=r351hf484d3e_0
  - bioconductor-rtracklayer=1.42.1=r351h9d9f1b6_1
  - bioconductor-s4vectors=0.20.1=r351h14c3975_0
  - bioconductor-summarizedexperiment=1.12.0=r351_0
  - bioconductor-xvector=0.22.0=r351h14c3975_0
  - bioconductor-zlibbioc=1.28.0=r351h14c3975_0
  - biopython=1.76=py37h516909a_0
  - boost=1.72.0=py37h9de70de_0
  - boost-cpp=1.72.0=h8e57a91_0
  - boto3=1.12.17=py_0
  - botocore=1.15.17=py_0
  - bwa=0.7.17=hed695b0_7
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.2=hecda079_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2020.4.5.2=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - chardet=3.0.4=py37_1003
  - cmake=3.16.4=h28c56e5_0
  - configargparse=1.0=py_0
  - cryptography=2.8=py37h72c5cf5_1
  - curl=7.68.0=hf8cf82a_0
  - datrie=0.8=py37h516909a_0
  - decorator=4.4.2=py_0
  - docutils=0.15.2=py37_0
  - dropbox=9.4.0=py_0
  - expat=2.2.9=he1b5a44_2
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - fonts-conda-forge=1=0
  - freebayes=1.3.2=py37hc088bd4_0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - ftputil=3.4=py_0
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_17
  - gdk-pixbuf=2.38.2=h3f25603_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_5
  - gfortran_linux-64=7.3.0=h553295d_17
  - ghostscript=9.22=hf484d3e_1001
  - giflib=5.2.1=h516909a_2
  - gitdb=4.0.2=py_0
  - gitpython=3.1.0=py_0
  - glib=2.58.3=py37h6f030ca_1002
  - gobject-introspection=1.58.2=py37h5503ade_1002
  - google-api-core=1.16.0=py37_1
  - google-auth=1.11.2=py_0
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.26.0=py_0
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.51.0=py37_1
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.42.3=h0511662_0
  - gsl=2.5=h294904e_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_17
  - harfbuzz=2.4.0=h9f30f68_3
  - htslib=1.10.2=h78d89cc_0
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - imagemagick=7.0.10_0=pl526ha9fe49d_0
  - importlib_metadata=1.5.0=py37_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h14c3975_2001
  - jinja2=2.11.1=py_0
  - jmespath=0.9.5=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py37_0
  - jupyter_core=4.6.3=py37_0
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=15_openblas
  - libcblas=3.8.0=15_openblas
  - libcroco=0.6.13=h8d621e5_0
  - libcurl=7.68.0=hda55be3_0
  - libdeflate=1.3=h516909a_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - libidn2=2.3.0=h516909a_0
  - liblapack=3.8.0=15_openblas
  - libopenblas=0.3.8=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.11.4=h8b12597_0
  - librsvg=2.46.4=h33a7fed_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.34.0=h516909a_0
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - make=4.3=h516909a_0
  - markupsafe=1.1.1=py37h516909a_0
  - multidict=4.7.5=py37h516909a_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - numpy=1.18.1=py37h95a1406_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.1=py37hb3f55d8_0
  - pango=1.42.4=ha030887_1
  - parallel=20200122=0
  - paramiko=2.7.1=py37_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - prettytable=0.7.2=py_3
  - protobuf=3.11.4=py37he1b5a44_0
  - psutil=5.7.0=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyfaidx=0.5.8=py_1
  - pygments=2.6.1=py_0
  - pygraphviz=1.3=py37h14c3975_1
  - pynacl=1.3.0=py37h516909a_1001
  - pyopenssl=19.1.0=py_1
  - pyrsistent=0.15.7=py37h516909a_0
  - pysam=0.15.3=py37hbcae180_3
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h357f687_4_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyvcf=0.6.8=py37_1000
  - pyyaml=5.3=py37h516909a_0
  - r-askpass=1.1=r35hcdcec82_1
  - r-assertthat=0.2.1=r35h6115d3f_1
  - r-backports=1.1.5=r35hcdcec82_0
  - r-base=3.5.1=hc461eb7_1012
  - r-bh=1.72.0_3=r35h6115d3f_0
  - r-bitops=1.0_6=r35hcdcec82_1003
  - r-brew=1.0_6=r35h6115d3f_1002
  - r-callr=3.4.2=r35h6115d3f_0
  - r-catools=1.17.1.4=r35h0357c0b_0
  - r-circlize=0.4.8=r35h6115d3f_0
  - r-cli=2.0.2=r35h6115d3f_0
  - r-clipr=0.7.0=r35h6115d3f_0
  - r-clisymbols=1.2.0=r35h6115d3f_1002
  - r-clue=0.3_57=r35h516909a_1
  - r-cluster=2.1.0=r35h9bbef5b_2
  - r-colorspace=1.4_1=r35hcdcec82_1
  - r-commonmark=1.7=r35hcdcec82_1001
  - r-covr=3.5.0=r35h0357c0b_0
  - r-cowplot=1.0.0=r35h6115d3f_1
  - r-crayon=1.3.4=r35h6115d3f_1002
  - r-crosstalk=1.0.0=r35h6115d3f_1002
  - r-curl=4.3=r35hcdcec82_0
  - r-data.table=1.12.6=r35hcdcec82_0
  - r-desc=1.2.0=r35h6115d3f_1002
  - r-devtools=2.2.2=r35h6115d3f_0
  - r-digest=0.6.25=r35h0357c0b_0
  - r-dplyr=0.8.5=r35h0357c0b_0
  - r-dt=0.12=r35h6115d3f_0
  - r-ellipsis=0.3.0=r35hcdcec82_0
  - r-evaluate=0.14=r35h6115d3f_1
  - r-fansi=0.4.1=r35hcdcec82_0
  - r-farver=2.0.3=r35h0357c0b_0
  - r-fastmap=1.0.1=r35h0357c0b_0
  - r-formatr=1.7=r35h6115d3f_1
  - r-fs=1.3.2=r35h0357c0b_0
  - r-futile.logger=1.4.3=r35h6115d3f_1002
  - r-futile.options=1.0.1=r35h6115d3f_1001
  - r-gdata=2.18.0=r35h6115d3f_1002
  - r-getoptlong=0.1.8=r35h6115d3f_0
  - r-ggplot2=3.0.0=r351h6115d3f_0
  - r-gh=1.1.0=r35h6115d3f_0
  - r-git2r=0.26.1=r35h5ca76e2_1
  - r-globaloptions=0.1.1=r35_0
  - r-glue=1.3.1=r35hcdcec82_1
  - r-gplots=3.0.3=r35h6115d3f_0
  - r-gtable=0.3.0=r35h6115d3f_2
  - r-gtools=3.8.1=r35hcdcec82_1003
  - r-htmltools=0.4.0=r35h0357c0b_0
  - r-htmlwidgets=1.5.1=r35h6115d3f_0
  - r-httpuv=1.5.2=r35h0357c0b_1
  - r-httr=1.4.1=r35h6115d3f_1
  - r-ini=0.3.1=r35h6115d3f_1002
  - r-jsonlite=1.6.1=r35hcdcec82_0
  - r-kernsmooth=2.23_16=r35hfa343cc_1
  - r-labeling=0.3=r35h6115d3f_1002
  - r-lambda.r=1.2.4=r35h6115d3f_0
  - r-later=1.0.0=r35h0357c0b_0
  - r-lattice=0.20_40=r35hcdcec82_0
  - r-lazyeval=0.2.2=r35hcdcec82_1
  - r-lifecycle=0.2.0=r35h6115d3f_0
  - r-magrittr=1.5=r35h6115d3f_1002
  - r-mass=7.3_51.5=r35hcdcec82_0
  - r-matrix=1.2_18=r35h7fa42b6_2
  - r-matrixstats=0.55.0=r35hcdcec82_0
  - r-mc2d=0.1_18=r35h6115d3f_1002
  - r-memoise=1.1.0=r35h6115d3f_1003
  - r-mgcv=1.8_24=r351h96ca727_0
  - r-mime=0.9=r35hcdcec82_0
  - r-munsell=0.5.0=r35h6115d3f_1002
  - r-mvtnorm=1.1_0=r35h9bbef5b_0
  - r-nlme=3.1_137=r351ha65eedd_0
  - r-openssl=1.4.1=r35h9c8475f_0
  - r-pheatmap=1.0.12=r35h6115d3f_1
  - r-pillar=1.4.3=r35h6115d3f_0
  - r-pkgbuild=1.0.6=r35h6115d3f_0
  - r-pkgconfig=2.0.3=r35h6115d3f_0
  - r-pkgload=1.0.2=r35h0357c0b_1001
  - r-plogr=0.2.0=r35h6115d3f_1002
  - r-plyr=1.8.6=r35h0357c0b_0
  - r-png=0.1_7=r35hcdcec82_1003
  - r-praise=1.0.0=r35h6115d3f_1003
  - r-prettyunits=1.1.1=r35h6115d3f_0
  - r-processx=3.4.2=r35hcdcec82_0
  - r-promises=1.1.0=r35h0357c0b_0
  - r-ps=1.3.2=r35hcdcec82_0
  - r-purrr=0.3.3=r35hcdcec82_0
  - r-r6=2.4.1=r35h6115d3f_0
  - r-rcmdcheck=1.3.3=r35h6115d3f_2
  - r-rcolorbrewer=1.1_2=r35h6115d3f_1002
  - r-rcpp=1.0.3=r35h0357c0b_0
  - r-rcurl=1.98_1.1=r35hcdcec82_0
  - r-remotes=2.1.1=r35h6115d3f_0
  - r-reshape2=1.4.3=r35h0357c0b_1004
  - r-rex=1.1.2=r35h6115d3f_1001
  - r-rjson=0.2.20=r35h0357c0b_1001
  - r-rlang=0.4.5=r35hcdcec82_0
  - r-roxygen2=7.0.2=r35h0357c0b_0
  - r-rprojroot=1.3_2=r35h6115d3f_1002
  - r-rstudioapi=0.11=r35h6115d3f_0
  - r-rversions=2.0.1=r35h6115d3f_0
  - r-scales=1.1.0=r35h6115d3f_0
  - r-sessioninfo=1.1.1=r35h6115d3f_1001
  - r-shape=1.4.4=r35_1002
  - r-shiny=1.4.0=r35h6115d3f_0
  - r-snow=0.4_3=r35h6115d3f_1001
  - r-sourcetools=0.1.7=r35he1b5a44_1001
  - r-stringi=1.4.6=r35h0e574ca_0
  - r-stringr=1.4.0=r35h6115d3f_1
  - r-sys=3.3=r35hcdcec82_0
  - r-testthat=2.3.2=r35h0357c0b_0
  - r-tibble=2.1.3=r35hcdcec82_1
  - r-tidyselect=1.0.0=r35h6115d3f_0
  - r-usethis=1.5.1=r35h6115d3f_1
  - r-utf8=1.1.4=r35hcdcec82_1001
  - r-vctrs=0.2.4=r35hcdcec82_0
  - r-viridislite=0.3.0=r35h6115d3f_1002
  - r-whisker=0.4=r35h6115d3f_0
  - r-withr=2.1.2=r35h6115d3f_1001
  - r-xml=3.99_0.3=r35hcdcec82_0
  - r-xml2=1.2.2=r35h0357c0b_0
  - r-xopen=1.0.0=r35h6115d3f_1002
  - r-xtable=1.8_4=r35h6115d3f_2
  - r-yaml=2.2.1=r35hcdcec82_0
  - r-zeallot=0.1.0=r35h6115d3f_1001
  - r-zoo=1.8_3=r351h96ca727_0
  - ratelimiter=1.2.0=py37_1000
  - readline=8.0=hf8c457e_0
  - requests=2.23.0=py37_0
  - rhash=1.3.6=h14c3975_1001
  - rsa=4.0=py_0
  - s3transfer=0.3.3=py37_0
  - samtools=1.10=h9402c20_2
  - scipy=1.4.1=py37h921218d_0
  - setuptools=46.0.0=py37hc8dfbb8_1
  - six=1.14.0=py37_0
  - smmap=3.0.1=py_0
  - snakemake=5.10.0=0
  - snakemake-minimal=5.10.0=py_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - tktable=2.10=h555a92e_3
  - toposort=1.5=py_3
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.7=py37_0
  - wget=1.20.1=h22169c7_0
  - whatshap=0.18=py37h6bb024c_0
  - wheel=0.34.2=py_1
  - wrapt=1.12.1=py37h516909a_0
  - xmlrunner=1.7.7=py_0
  - xopen=0.8.4=py37_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - yarl=1.3.0=py37h516909a_1000
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
prefix: /home/hashraf/miniconda3/envs/strandseqnation_30-7-20
