input_bam_location: "/g/korbel2/weber/MosaiCatcher_files/bam/"
output_location: "/g/korbel2/weber/MosaiCatcher_output/"
snv_sites_to_genotype: "/g/korbel2/weber/MosaiCatcher_files/snv_sites_to_genotype/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz"
reference: "/g/korbel2/weber/MosaiCatcher_files/refgenomes_human/hg38.no_alt.fa"
mosaicatcher: "/g/korbel2/weber/Gits/mosaicatcher/build/mosaic"
plot_script: "/g/korbel2/weber/Gits/mosaicatcher/R/qc.R"
sv_plot_script: "/g/korbel2/weber/Gits/mosaicatcher/R/chrom.R"
norm_script: "/g/korbel2/weber/Gits/mosaicatcher/R/norm.R"
samtools: "/biolo/ngs/bin/samtools"
bcftools: "/biolo/ngs/bin/bcftools"
variable_bins:
  "50000": "/g/korbel2/weber/workspace/pipeline/utils/variable_bins.GRCh38.50kb.bed"
  "100000": "/g/korbel2/weber/workspace/pipeline/utils/variable_bins.GRCh38.100kb.bed"
R_reference: "/home/tweber/.conda/envs/strandseqnation/lib/R/library/BSgenome.Hsapiens.UCSC.hg38/extdata/single_sequences.2bit"
bp_density:
  few: 0.2
  medium: 0.4
  many: 0.6
paired_end: true
ground_truth_clonal:
  RPE-BM510: ""
ground_truth_single_cell:
  RPE-BM510: ""
simulation_min_vaf: 0.01
simulation_max_vaf: 1
simulation_neg_binom_p:
  "50000": 0.4
  "100000": 0.3
  "500000": 0.1
simulation_min_reads_per_library: 500000
simulation_max_reads_per_library: 1000000
simulation_window_sizes:
  - 50000
  - 100000
simulation_cell_count: 100
simulation_alpha: 0.02
genome_size: 3000000000
chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
