# --------------------------------------------------------
# MosaiCatcher pipeline Configuration
# --------------------------------------------------------

# MosaiCatcher version
version: 2.2.1

# Ashleys-QC pipeline version
ashleys_pipeline_version: 2.2.1

# Email for notifications about the pipeline's status
email: ""

# List of samples to process if multiple are specified
samples_to_process: []

# --------------------------------------------------------
# Data location & I/O
# --------------------------------------------------------

# Absolute path to the data location (modify as needed)
data_location: ".tests/data_CHR17"

# Directory to publish important data (e.g., stats, plots, counts). Leave empty if not required.
publishdir: ""

# --------------------------------------------------------
# Ashleys-QC upstream pipeline
# --------------------------------------------------------

# Legacy folder organisation: bam/ and selected/ folder - Mutually exclusive with ashleys_pipeline
input_bam_legacy: False

# Enable/Disable ashleys-qc-pipeline module loading to start pipeline from FASTQ files
ashleys_pipeline: False

# Target only output of ashleys-qc-pipeline
ashleys_pipeline_only: False

# Threshold for Ashleys-qc binary classification
ashleys_threshold: 0.5

# Enable or disable FastQC analysis
MultiQC: False

# --------------------------------------------------------
# GENECORE Configuration
# --------------------------------------------------------

genecore: False
genecore_date_folder: ""
genecore_prefix: "/g/korbel/STOCKS/Data/Assay/sequencing/2023"
genecore_regex_element: "PE20"

# --------------------------------------------------------
# Reference Data Configuration
# --------------------------------------------------------

# Reference genome used by BWA to map FASTQ files
reference: "hg38"

# Reference assemblies data
references_data:
  "hg38":
    reference_fasta: "workflow/data/ref_genomes/hg38.fa"
    R_reference: "BSgenome.Hsapiens.UCSC.hg38"
    segdups: "workflow/data/segdups/segDups_hg38_UCSCtrack.bed.gz"
    snv_sites_to_genotype: ""
    reference_file_location: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/analysisSet/hg38.analysisSet.fa.gz

  "hg19":
    reference_fasta: "workflow/data/ref_genomes/hg19.fa"
    R_reference: "BSgenome.Hsapiens.UCSC.hg19"
    segdups: "workflow/data/segdups/segDups_hg19_UCSCtrack.bed.gz"
    snv_sites_to_genotype: ""
    reference_file_location: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/analysisSet/hg19.p13.plusMT.no_alt_analysis_set.fa.gz
  "T2T":
    reference_fasta: "workflow/data/ref_genomes/T2T.fa"
    R_reference: "BSgenome.T2T.CHM13.V2"
    # R_reference_tarball: "/g/korbel2/weber/MosaiCatcher_files/EXTERNAL_DATA/R_reference//BSgenome.T2T.CHM13.V2_1.0.0.tar.gz"
    segdups: "workflow/data/segdups/segDups_T2T_UCSCtrack.bed.gz"
    snv_sites_to_genotype: ""
    reference_file_location: https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz
  "mm10":
    reference_fasta: "workflow/data/ref_genomes/mm10.fa"
    R_reference: "BSgenome.Mmusculus.UCSC.mm10"
    segdups: "workflow/data/segdups/segDups_mm10_UCSCtrack.bed.gz"
    snv_sites_to_genotype: ""
    reference_file_location: https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.fa.gz

# List of chromosomes to process
chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY

# Specify any chromosomes to exclude from processing
chromosomes_to_exclude: []

# --------------------------------------------------------
# Counts Configuration
# --------------------------------------------------------

# Enable or disable multistep normalization analysis
multistep_normalisation: False

# Advanced parameters for multi-step normalisation
multistep_normalisation_options:
  min_reads_bin: 5
  n_subsample: 1000
  min_reads_cell: 100000

# Normalize or not mosaic counts using HGSVC-based reference file
hgsvc_based_normalized_counts: True

# Window size used by the mosaic binning algorithm
window: 200000

# Enable / Disable blacklisting of difficult mappable regions
blacklist_regions: True

# Enable or disable hand selection through the Jupyter Notebook
hand_selection: False

# --------------------------------------------------------
# SV Calling Configuration
# --------------------------------------------------------

# Enable / Disable multistep normalisation output for SV calling
multistep_normalisation_for_SV_calling: False

methods:
  lenient:
    method_name: "simpleCalls_llr4_poppriorsTRUE_haplotagsTRUE_gtcutoff0_regfactor6_filterFALSE"
    llr: 4
    poppriors: TRUE
    haplotags: TRUE
    gtcutoff: 0
    regfactor: 6
    filter: "FALSE"

  stringent:
    method_name: "simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE"
    llr: 4
    poppriors: TRUE
    haplotags: TRUE
    gtcutoff: 0.05
    regfactor: 6
    filter: "TRUE"

# joint segmentation
min_diff_jointseg: 0.1

# single segmentation
min_diff_singleseg: 0.5

# SCE cutoff
additional_sce_cutoff: 20000000

# SCE min distance
sce_min_distance: 500000

# --------------------------------------------------------
# Downstream modules configuration - genome browsing
# --------------------------------------------------------
genome_browsing_files_generation: False

# --------------------------------------------------------
# Downstream modules configuration - ArbiGent
# --------------------------------------------------------

# ArbiGent (Arbitrary-segments genotyping) mode of execution
arbigent: False
# Arbigent default BED file, can be changed and adapted based on user question
arbigent_bed_file: "workflow/data/arbigent/manual_segmentation.bed"

# Arbigent Data
arbigent_data:
  arbigent_mapability_track: workflow/data/arbigent/mapping_counts_allchrs_hg38.txt
  arbigent_mapability_track_h5: workflow/data/arbigent/mapping_counts_allchrs_hg38.h5

# --------------------------------------------------------
# Downstream modules configuration - scNOVA
# --------------------------------------------------------

# Enable / Disable scNOVA - require scNOVA_input_user/input_subclonality.txt file
scNOVA: False

# Scripts location
scNOVA_scripts:
  generate_CN_for_CNN: "workflow/scripts/scNOVA_scripts/generate_CN_for_CNN.R"
  generate_CN_for_chromVAR: "workflow/scripts/scNOVA_scripts/generate_CN_for_chromVAR.R"
  count_sort_annotate_geneid: "workflow/scripts/scNOVA_scripts/count_sort_annotate_geneid.R"
  count_sort_label: "workflow/scripts/scNOVA_scripts/count_sort_label.R"
  count_norm: "workflow/scripts/scNOVA_scripts/count_norm.R"
  feature_sc_var: "workflow/scripts/scNOVA_scripts/feature_sc_var.R"
  combine_features: "workflow/scripts/scNOVA_scripts/combine_features.R"
  annot_expressed: "workflow/scripts/scNOVA_scripts/annot_expressed.R"
  infer_diff_gene_expression: "workflow/scripts/scNOVA_scripts/infer_diff_gene_expression.R"
  count_sort_annotate_chrid_CREs: "workflow/scripts/scNOVA_scripts/count_sort_annotate_chrid_CREs.R"
  infer_diff_gene_expression_alt: "workflow/scripts/scNOVA_scripts/infer_diff_gene_expression_alt.R"

# --------------------------------------------------------
# Plotting options
# --------------------------------------------------------

# Split / Do not split QC counts plot into single individual images (limit jobs)
split_qc_plot: False

plottype_counts:
  - "raw"
  - "normalised"

plottype_consistency:
  - "byaf"
  - "bypos"

plottype_clustering:
  - "position"
  - "chromosome"

scTRIP_multiplot: False

# --------------------------------------------------------
# Internal Parameters
# --------------------------------------------------------

# Is the pipeline used as a submodule in mosaicatcher-pipeline?
mosaicatcher_pipeline: True

# Overwrite ASHLEYS PREDICTIONS for GitHub & smoke dataset purpose
use_light_data: False

# For snakemake linting
abs_path: "/"

# Option to display all potential options - listed in config_metadata.yaml
list_commands: False
