#######################################
#   MOSAICATCHER CONFIGURATION FILE.  #
#######################################

mail: ""

#######################################
## Command-line options
#######################################

### Modes ["count", "segmentation", "mosaiclassifier"]
mode: "mosaiclassifier"
### Plot enabled [True] or disabled [False]
plot: False
### Enable / Disable comparison for each BAM file between folder name & SM tag
check_sm_tag: True
### Enable / Disable download of BAM examples (RPE-BM510)
dl_bam_example: False
### Enable / Disable download of external files (1000G SNV & Fasta ref genome)
dl_external_files: False

## Input BAM location
input_bam_location: ".tests/data/"
## Output location
output_location: ".tests/output/"

# External files
## 1000G SNV sites to genotype : https://sandbox.zenodo.org/record/1060653/files/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz
snv_sites_to_genotype: sandbox.zenodo.org/record/1074721/files/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz

# Reference genome : https://sandbox.zenodo.org/record/1060653/files/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
reference: sandbox.zenodo.org/record/1074721/files/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna

# Chromosomes list to process
chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX

##############################
# Advanced configuration.  #
##############################

# Enable conda & singularity usage
use-conda: True
use-singularity: True
containerized: False
singularity-args: "-B /g:/g"
latency-wait: 60

# Default conda frontend
conda-frontend: "conda"

# Print shell commands
printshellcmds: True

# External static data
# R Ref
R_reference: "BSgenome.Hsapiens.UCSC.hg38"
# SegDups file
segdups: "workflow/data/segdups/segDups_hg38_UCSCtrack.bed.gz"

# Strandphaser
git_commit_strandphaser: "69c9fb4"
git_repo_strandphaser: "https://github.com/daewoooo/StrandPhaseR"
paired_end: True

# CHECKME : Parameters optimization ?
# PARAMETERS

## WINDOW
window: 100000

## METHODS
methods:
  - "simpleCalls_llr4_poppriorsTRUE_haplotagsTRUE_gtcutoff0_regfactor6_filterFALSE"
  - "simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE"

llr: 4
poppriors: TRUE
haplotags:
  - TRUE
  - FALSE
gtcutoff:
  - 0
  - 0.05
regfactor: 6
filter:
  - TRUE
  - FALSE

## BPDENS
### JOINT SEG
min_diff_jointseg: 0.1
### SINGLE SEG
min_diff_singleseg: 0.5
### SCE CUTOFF
additional_sce_cutoff: 20000000
### SCE MIN DISTANCE
sce_min_distance: 500000
