# Cluster command
cluster: mkdir -p logs/{rule} errors/{rule} &&
  sbatch
  --partition={resources.partition}
  --qos={resources.qos}
  --cpus-per-task={threads}
  --mem={resources.mem_mb}
  --job-name=smk-{rule}-{wildcards}
  --output=logs/{rule}/%j.out
  --error=errors/{rule}/%j.error
  --time={resources.time}
  --constraint={resources.constraint}

# Default ressources for all rules
default-resources:
  - partition=htc
  - qos=normal
  - mem_mb=1000
  - time="00:30:00"
  - constraint=""

# set-resources:
#   ashleys_mark_duplicates: constraint="rome"

max-jobs-per-second: 100
max-status-checks-per-second: 100
local-cores: 1
latency-wait: 60
jobs: 200

# 5 attempts to restart to correspond to the progressive memory increase solving OOM
restart-times: 5
keep-going: True
# rerun-incomplete: True
# scheduler: greedy

use-conda: true
conda-frontend: "conda"
use-singularity: true
singularity-args: "-B /g:/g,/scratch:/scratch"
